### ISSUE TITLE
🐛 无法运行

### ISSUE THREAD

**Issue by pecliu** [yutto-dev/bilili#256]
### 问题简述

root@VM-55-178-centos /data/bilibili # bilili -v
Traceback (most recent call last):
  File "/usr/local/bin/bilili", line 7, in <module>
    from bilili.__main__ import main
  File "/usr/local/lib/python3.6/site-packages/bilili/__main__.py", line 144
    if (avid_match := regex.acg_video.av.origin.match(args.url)) or \
                   ^
SyntaxError: invalid syntax

### 复现方式

pip3 install bilili 后

### 环境信息

-  OS: centos
-  Python: Python 版本号 (`python --version`) 3.11
-  bilili: bilili 版本号 (`bilili -v`) 报错
-  FFmpeg: FFmpeg 版本号 (`ffmpeg -version`)N-67885-gcc86343b96-static
-  如果是显示相关问题
    -  Shell: Shell 类型 (`echo $SHELL`)/bin/bash
    -  Terminal: 终端类型
-  Others: 其它信息

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/bilili) 与[文档](https://bilili.nyakku.moe/)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 bilili 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/bilili/issues) 和 [discussion](https://github.com/yutto-dev/bilili/discussions) 中并没有重复问题

**Comment by pecliu** [comment]
> ```
> Traceback (most recent call last):
> File "/usr/local/bin/bilili", line 7, in
> from bilili.main import main
> File "/usr/local/lib/python3.6/site-packages/bilili/main.py", line 144
> if (avid_match := regex.acg_video.av.origin.match(args.url)) or
> ^
> SyntaxError: invalid syntax
> ```
> 
> 报错写着 python3.6 你跟我说你用的是 python3.11？明确说了不支持 python3.6，最低支持 3.8

检查了下。安装了 3.11，但是之前默认的软链指向了 3.6
调整软链到 3.11 后解决，可以正常使用
